# Generated by Django 5.2.12 on 2026-03-05 16:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('master', 'Master'), ('admin', 'Admin'), ('consultant', 'Consultant')], default='consultant', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='AiReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('period_start', models.CharField(max_length=20)),
                ('period_end', models.CharField(max_length=20)),
                ('stats', models.TextField(default='{}')),
                ('ai_conclusion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('student', 'Student Visa & University'), ('paye', 'PAYE Tax Refund'), ('self', 'Self Assessment Tax'), ('company', 'Company Accounting'), ('general', 'General Inquiry')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('conversation_history', models.TextField(default='[]')),
                ('context', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tg_id', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('message_count', models.IntegerField(default=0)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tg_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('sender_name', models.CharField(default='Admin', max_length=100)),
                ('sent', models.BooleanField(default=False)),
                ('account_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pending_sends',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_uz', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, db_column='service_keywords', default='')),
                ('ai_system_prompt', models.TextField(blank=True, default='')),
                ('ai_collect_items', models.TextField(blank=True, default='')),
                ('ai_documents_list', models.TextField(blank=True, default='')),
                ('ai_strict_flow', models.BooleanField(default=False)),
                ('badge_color', models.CharField(default='general', max_length=20)),
                ('icon_emoji', models.CharField(blank=True, default='📋', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_definitions',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_column='tg_id', unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('language_code', models.CharField(db_column='language', default='en', max_length=10)),
                ('is_bot', models.BooleanField(default=False)),
                ('profile_data', models.TextField(default='{}')),
                ('chat_mode', models.CharField(default='menu', max_length=20)),
                ('linked_account', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='core.case')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adminuser')),
            ],
            options={
                'db_table': 'case_tracking',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, db_column='filename', max_length=500, null=True)),
                ('file_type', models.CharField(blank=True, db_column='doc_type', max_length=50, null=True)),
                ('telegram_file_id', models.TextField(db_column='file_id')),
                ('file_unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('media_type', models.CharField(default='document', max_length=20)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(db_column='created_at', default=datetime.datetime.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.case')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_user', models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.adminuser')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('payment_date', models.DateTimeField(db_column='created_at', default=datetime.datetime.now)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, db_column='proof_file_id', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.case')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(db_column='type', max_length=50)),
                ('due_at', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.case')),
            ],
            options={
                'db_table': 'reminders',
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(db_column='order', default=0)),
                ('label', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_uz', models.TextField(blank=True, default='')),
                ('is_required', models.BooleanField(default=True)),
                ('is_final', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.servicedefinition')),
            ],
            options={
                'db_table': 'service_steps',
                'ordering': ['step_number'],
                'unique_together': {('service', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CaseTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, db_column='note', default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='core.case')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adminuser')),
                ('tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.casetracking')),
                ('from_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.servicestep')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.servicestep')),
                ('to_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.servicestep')),
            ],
            options={
                'db_table': 'case_tracking_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='casetracking',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicestep'),
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Admin', max_length=100)),
                ('note_text', models.TextField(db_column='content')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adminuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.tguser')),
            ],
            options={
                'db_table': 'client_notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.tguser'),
        ),
        migrations.CreateModel(
            name='UserAiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_data', models.TextField(default='{}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to='core.tguser')),
            ],
            options={
                'db_table': 'user_ai_profiles',
            },
        ),
        migrations.CreateModel(
            name='AdminAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.adminuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.tguser')),
            ],
            options={
                'db_table': 'admin_assignments',
                'unique_together': {('admin', 'user')},
            },
        ),
    ]
