# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_case_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraiprofile",
            name="pinned_data",
            field=models.TextField(default="[]"),
        ),
    ]
