# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_aiprofile_pinned_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
