# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_document_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="ai_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
