# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_case_ai_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tguser",
            name="profile_photo_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tguser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
