# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_tguser_profile_photo_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="theme_mode",
            field=models.CharField(default="dark", max_length=10),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="theme_dark",
            field=models.CharField(default="default", max_length=20),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="theme_light",
            field=models.CharField(default="default", max_length=20),
        ),
    ]
