# Generated by Django 6.0.3 on 2026-03-31 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_aisettings_master_switch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("name_ru", models.CharField(blank=True, max_length=100, null=True)),
                ("name_uz", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "icon_emoji",
                    models.CharField(blank=True, default="📂", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="case",
            name="service_definition",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked ServiceDefinition (set by simplified bot flow)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="core.servicedefinition",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="theme_dark",
            field=models.CharField(default="blue", max_length=20),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="theme_light",
            field=models.CharField(default="blue", max_length=20),
        ),
        migrations.AlterField(
            model_name="case",
            name="service",
            field=models.CharField(
                choices=[
                    ("student", "Student Visa & University"),
                    ("paye", "PAYE Tax Refund"),
                    ("schengen", "Schengen Visa"),
                    ("self", "Self Assessment Tax"),
                    ("company", "Company Accounting"),
                    ("general", "General Inquiry"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="groupbotmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="groupchat",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="groupcooldown",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject selected in simplified bot flow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="core.subject",
            ),
        ),
        migrations.AddField(
            model_name="servicedefinition",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject category this service belongs to (used by simplified bot flow)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="core.subject",
            ),
        ),
    ]
