# Generated by Django 6.0.3 on 2026-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_subject_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingsend",
            name="send_type",
            field=models.CharField(
                choices=[("text", "Text"), ("voice", "Voice")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pendingsend",
            name="voice_file",
            field=models.FileField(blank=True, null=True, upload_to="pending_voice/"),
        ),
        migrations.AlterField(
            model_name="pendingsend",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
