# Generated by Django 6.0.3 on 2026-04-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_pending_send_voice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="language_code",
            field=models.CharField(
                blank=True, db_column="language", default="", max_length=10
            ),
        ),
    ]
