# Generated by Django 6.0.3 on 2026-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tguser_language_blank_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "faq_entries",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="aisettings",
            name="faq_unanswered_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Shown when a user asks a question not found in the FAQ. Write in any language — the bot will translate it for the user. Leave blank for a built-in default.",
            ),
        ),
    ]
