# Generated by Django 6.0.3 on 2026-04-14 19:15

from django.db import migrations


def clear_language_codes(apps, schema_editor):
    """
    Reset all existing users' language_code to '' so they go through
    the new explicit language-selection step on their next interaction.
    Languages chosen via the new flow are saved back to the DB, so this
    only forces a one-time re-selection.
    """
    TgUser = apps.get_model('core', 'TgUser')
    TgUser.objects.all().update(language_code='')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_faqentry_aisettings_faq_text"),
    ]

    operations = [
        migrations.RunPython(clear_language_codes, migrations.RunPython.noop),
    ]
