# Generated by Django 6.0.3 on 2026-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_clear_existing_language_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="notification_code",
            field=models.CharField(
                blank=True,
                help_text="Temporary 5-digit code for linking Telegram account",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="notification_code_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Telegram chat ID for receiving notifications via bot",
                null=True,
            ),
        ),
    ]
